version: "3.3"
services:
    web:
        depends_on:
            - db
        image: webservice:lastest
        container_name: apps
        environment:
            JDBC_URL: jdbc:mysql://db:3306/
            DATABASE_NAME: kringetify_soap_service
            JDBC_USER: kringetify
            JDBC_PASS: soap_service
        ports:
            - "8080:8080"
    db:
        image: mysql:latest
        container_name: mysql
        volumes:
            - ./com/kringetify/database/kringetify_soap.sql:/data/apps/soap.sql
        command: --init-file /data/apps/soap.sql
        environment:
            MYSQL_ROOT_PASSWORD: admin_kringetify
            MYSQL_DATABASE: kringetify_soap_service
            MYSQL_USER: kringetify
            MYSQL_PASSWORD: soap_service
        ports:
            - "3306:3306"
